import { Metadata } from "next";
import './globals.css';
import './embla.css'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import React from "react";
import { Main } from "@/Components/Provider/Main";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={``}>
        <Main>
          {children}
        </Main>
      </body>
    </html>
  );
}
